require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'example' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )
    
    # Optimize MLX Swift package compilation
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # General optimizations for all targets
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        config.build_settings['ENABLE_NS_ASSERTIONS'] = 'NO'
        config.build_settings['VALIDATE_PRODUCT'] = 'NO'
        config.build_settings['MTL_ENABLE_DEBUG_INFO'] = 'NO'
        
        # MLX-specific optimizations
        if target.name.include?('MLX') || target.name.include?('mlx-swift') || target.name.include?('swift-transformers')
          config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
          config.build_settings['SWIFT_WHOLE_MODULE_OPTIMIZATION'] = 'YES'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['ENABLE_LIBRARY_EVOLUTION'] = 'YES'
          config.build_settings['SWIFT_SERIALIZE_DEBUGGING_OPTIONS'] = 'NO'
          config.build_settings['SWIFT_ENABLE_BATCH_MODE'] = 'YES'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -j4 -enable-library-evolution'
          
          # Reduce memory usage during compilation
          config.build_settings['SWIFT_EXEC'] = '$(TOOLCHAIN_DIR)/usr/bin/swiftc'
          
          # Disable debug info for release builds to speed up compilation
          if config.name == 'Release'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
            config.build_settings['SWIFT_DEBUG_INFORMATION_FORMAT'] = 'line-tables-only'
          end
        end
      end
    end
  end
end
